server.port=8080
spring.data.mongodb.uri=mongodb+srv://ajaykapasiyadev_db_user:fxuo1CZgcs5jqBRk@cluster0.a30cmgn.mongodb.net/journaldb?retryWrites=true&w=majority
spring.data.mongodb.auto-index-creation=true

#server.error.include-message=always
#server.error.include-binding-errors=always
